### ISSUE TITLE
I got a BEDROC score that is larger than 1

### ISSUE THREAD

**Issue by xuzhang5788** [richlewis42/scikit-chem#76]
I implemented your metrics.py into my deep learning model, I got the BEDROC score that is larger than 1. I don't know why. Do I need to sort y_pred?

**Comment by richlewis42** [comment]
Hi, sorry to have not got back to you until now.  There is a huge update to this library that I haven't released yet which has a complete rewrite of this. I would recommend using rdkit's implementation rdkit.ML.Scoring.Scoring.CalcBEDROC rather than this one, at least until I get this next version out.
